import { defineConfig } from 'tsup';

export default defineConfig({
  entry: ['server.ts'],
  outDir: 'dist-server',
  format: ['cjs'],
  target: 'node20',
  platform: 'node',
  bundle: true,
  sourcemap: false,
  minify: false,
  // better-sqlite3 est un addon natif (.node) — il doit rester dans node_modules
  // electron-builder le copie via asarUnpack
  external: [
    'better-sqlite3',
    'electron',
  ],
  // Éviter de bundler vite (utilisé uniquement en dev pour HMR)
  noExternal: [],
  esbuildOptions(options) {
    // Supprimer les warnings pour les imports dynamiques de vite (dev uniquement)
    options.banner = {
      js: '// BERAMETHODE server bundle — generated by tsup',
    };
  },
});
