import { Machine, Guide, Translations } from '../types';

export const TRANSLATIONS = {
    fr: {
        title: 'INGÉNIERIE BERAMETHODE',
        dashboard: 'Tableau de bord',
        library: 'Bibliothèque',
        coupe: 'La Coupe',
        effectifs: 'Effectifs',
        objectifs: 'Objectifs',
        atelier: 'Chef Atelier',
        ingenierie: 'Ingénierie',
        admin: 'Admin',
        profile: 'Profil',
        config: 'Paramètres',
        export: 'Export Stocks',
        suivi: 'Suivi Production',
        planning: 'Planning',
        magasin: 'Magasin',
        logout: 'Déconnexion',
        langBtn: 'AR',
        saved: 'Sauvegardé',
        saving: 'Enregistrement...',
        unsaved: 'Non sauvegardé',
        fiche: 'Fiche Technique',
        gamme: 'Gamme de Montage',
        analyse: 'Analyse',
        equilibrage: 'Équilibrage',
        implantation: 'Implantation',
        couts: 'Coûts & Budget',
        save: 'Enregistrer',
        next: 'Suivant',
        finish: 'Terminer',
        undo: 'Annuler (Ctrl+Z)',
        redo: 'Rétablir (Ctrl+Y)',
        refresh: 'Actualiser',
        configuration: 'Configuration',
        prev: 'Précédent'
    },
    ar: {
        title: 'بـيـراميـثـود',
        dashboard: 'لوحة التحكم',
        library: 'المكتبة',
        coupe: 'القص',
        effectifs: 'التأطير',
        objectifs: 'الأهداف',
        atelier: 'رئيس الورشة',
        ingenierie: 'الورشة',
        admin: 'المشرف',
        profile: 'حسابي',
        config: 'الإعدادات',
        export: 'تصدير المخزون',
        suivi: 'تتبع الإنتاج',
        planning: 'التخطيط',
        magasin: 'المخزن',
        saved: 'محفوظ',
        saving: 'جارٍ الحفظ...',
        unsaved: 'غير محفوظ',
        logout: 'تسجيل الخروج',
        langBtn: 'FR',
        fiche: 'الملف التقني',
        gamme: 'سلسلة العمليات',
        analyse: 'التحليل',
        equilibrage: 'التوازن',
        implantation: 'التخطيط',
        couts: 'التكاليف والميزانية',
        save: 'حفظ',
        next: 'التالي',
        finish: 'إنهاء',
        undo: 'تراجع (Ctrl+Z)',
        redo: 'إعادة (Ctrl+Y)',
        refresh: 'تحديث العرض',
        configuration: 'الإعدادات',
        prev: 'السابق'
    },
    es: {
        title: 'INGENIERÍA BERAMETHODE',
        dashboard: 'Panel',
        library: 'Biblioteca',
        coupe: 'Corte',
        effectifs: 'Personal',
        objectifs: 'Objetivos',
        atelier: 'Jefe de Taller',
        ingenierie: 'Ingeniería',
        admin: 'Admin',
        profile: 'Perfil',
        config: 'Ajustes',
        export: 'Exportar Stock',
        suivi: 'Seguimiento Producción',
        planning: 'Planificación',
        magasin: 'Almacén',
        logout: 'Cerrar sesión',
        langBtn: 'EN',
        saved: 'Guardado',
        saving: 'Guardando...',
        unsaved: 'Sin guardar',
        fiche: 'Ficha Técnica',
        gamme: 'Gama de Montaje',
        analyse: 'Análisis',
        equilibrage: 'Equilibrado',
        implantation: 'Implantación',
        couts: 'Costes y Presupuesto',
        save: 'Guardar',
        next: 'Siguiente',
        finish: 'Finalizar',
        undo: 'Deshacer (Ctrl+Z)',
        redo: 'Rehacer (Ctrl+Y)',
        refresh: 'Actualizar',
        configuration: 'Configuración',
        prev: 'Anterior'
    },
    en: {
        title: 'BERAMETHODE ENGINEERING',
        dashboard: 'Dashboard',
        library: 'Library',
        coupe: 'Cutting',
        effectifs: 'Staffing',
        objectifs: 'Objectives',
        atelier: 'Workshop Lead',
        ingenierie: 'Engineering',
        admin: 'Admin',
        profile: 'Profile',
        config: 'Settings',
        export: 'Stock Export',
        suivi: 'Production Tracking',
        planning: 'Planning',
        magasin: 'Warehouse',
        logout: 'Log out',
        langBtn: 'AR',
        saved: 'Saved',
        saving: 'Saving...',
        unsaved: 'Unsaved',
        fiche: 'Technical Sheet',
        gamme: 'Assembly Sequence',
        analyse: 'Analysis',
        equilibrage: 'Balancing',
        implantation: 'Layout',
        couts: 'Costs & Budget',
        save: 'Save',
        next: 'Next',
        finish: 'Finish',
        undo: 'Undo (Ctrl+Z)',
        redo: 'Redo (Ctrl+Y)',
        refresh: 'Refresh',
        configuration: 'Configuration',
        prev: 'Previous'
    },
    pt: {
        title: 'ENGENHARIA BERAMETHODE',
        dashboard: 'Painel',
        library: 'Biblioteca',
        coupe: 'Corte',
        effectifs: 'Efetivos',
        objectifs: 'Objetivos',
        atelier: 'Chefe de Oficina',
        ingenierie: 'Engenharia',
        admin: 'Admin',
        profile: 'Perfil',
        config: 'Definições',
        export: 'Exportar Stock',
        suivi: 'Acompanhamento Produção',
        planning: 'Planeamento',
        magasin: 'Armazém',
        logout: 'Terminar sessão',
        langBtn: 'EN',
        saved: 'Guardado',
        saving: 'A guardar...',
        unsaved: 'Não guardado',
        fiche: 'Ficha Técnica',
        gamme: 'Sequência de Montagem',
        analyse: 'Análise',
        equilibrage: 'Balanceamento',
        implantation: 'Implantação',
        couts: 'Custos e Orçamento',
        save: 'Guardar',
        next: 'Seguinte',
        finish: 'Concluir',
        undo: 'Anular (Ctrl+Z)',
        redo: 'Refazer (Ctrl+Y)',
        refresh: 'Atualizar',
        configuration: 'Configuração',
        prev: 'Anterior'
    },
    tr: {
        title: 'BERAMETHODE MÜHENDİSLİK',
        dashboard: 'Gösterge Paneli',
        library: 'Kütüphane',
        coupe: 'Kesim',
        effectifs: 'Personel',
        objectifs: 'Hedefler',
        atelier: 'Atölye Şefi',
        ingenierie: 'Mühendislik',
        admin: 'Yönetici',
        profile: 'Profil',
        config: 'Ayarlar',
        export: 'Stok Dışa Aktar',
        suivi: 'Üretim Takibi',
        planning: 'Planlama',
        magasin: 'Depo',
        logout: 'Çıkış',
        langBtn: 'EN',
        saved: 'Kaydedildi',
        saving: 'Kaydediliyor...',
        unsaved: 'Kaydedilmedi',
        fiche: 'Teknik Föy',
        gamme: 'Montaj Sırası',
        analyse: 'Analiz',
        equilibrage: 'Dengeleme',
        implantation: 'Yerleşim',
        couts: 'Maliyet ve Bütçe',
        save: 'Kaydet',
        next: 'İleri',
        finish: 'Bitir',
        undo: 'Geri Al (Ctrl+Z)',
        redo: 'Yinele (Ctrl+Y)',
        refresh: 'Yenile',
        configuration: 'Yapılandırma',
        prev: 'Önceki'
    },
} as const;

export type Lang = 'fr' | 'ar' | 'en' | 'es' | 'pt' | 'tr';

export const DEFAULT_MACHINES: Machine[] = [
    { id: '1', name: 'Surjeteuse 5 Fils', classe: '516', speed: 5500, speedMajor: 1.01, cofs: 1.19, active: true, machineCategory: 'Surjeteuse' },
    { id: '2', name: 'Surjeteuse 4 Fils', classe: '514', speed: 6000, speedMajor: 1.01, cofs: 1.17, active: true, machineCategory: 'Surjeteuse' },
    { id: '3', name: 'Surjeteuse 3 Fils', classe: '504', speed: 6000, speedMajor: 1.01, cofs: 1.15, active: true, machineCategory: 'Surjeteuse' },
    { id: '4', name: 'Piqueuse Plate', classe: '301', speed: 4500, speedMajor: 1.01, cofs: 1.17, active: true, machineCategory: 'Piqueuse' },
    { id: '5', name: 'Piqueuse Double Aig', classe: '316', speed: 3000, speedMajor: 1.01, cofs: 1.23, active: true, machineCategory: 'Piqueuse' },
    { id: '6', name: 'Colleteuse', classe: '602', speed: 4500, speedMajor: 1.01, cofs: 1.15, active: true, machineCategory: 'Colleteuse' },
    { id: '7', name: 'Chainette 2 Aig', classe: '402', speed: 4000, speedMajor: 1.01, cofs: 1.14, active: true, machineCategory: 'Chainette' },
    { id: '8', name: 'Point Invisible', classe: '101', speed: 2500, speedMajor: 1.01, cofs: 1.19, active: true, machineCategory: 'Spéciale' },
    { id: '9', name: 'Pose Bouton', classe: '107', speed: 1800, speedMajor: 1.01, cofs: 1.17, active: true, machineCategory: 'Spéciale' },
    { id: '10', name: 'Boutonnière Droite', classe: '304', speed: 2000, speedMajor: 1.01, cofs: 1.17, active: true, machineCategory: 'Spéciale' },
    { id: '11', name: 'Brideuse', classe: 'BR', speed: 2200, speedMajor: 1.01, cofs: 1.18, active: true, machineCategory: 'Spéciale' },
    { id: '12', name: 'ZigZag', classe: 'ZIGZAG', speed: 3000, speedMajor: 1.01, cofs: 1.19, active: true, machineCategory: 'Spéciale' },
    { id: '13', name: 'Manuel', classe: 'MAN', speed: 0, speedMajor: 1.01, cofs: 1.12, active: true, machineCategory: 'Manuel' },
    { id: '14', name: 'Repassage', classe: 'FER', speed: 0, speedMajor: 1.01, cofs: 1.12, active: true, machineCategory: 'Repassage' },
];

export const DEFAULT_GUIDES: Guide[] = [
    { id: 'g1', name: 'Guide Bordeur (Biais)', category: 'Bordeurs & Ourleurs', machineType: 'Piqueuse Plate (301)', description: 'Pour poser du biais à cheval (Ganser).', useCase: 'Encolure, Emmanchure' },
    { id: 'g2', name: 'Pied Compensé (1/16 - 1mm)', category: 'Surpiqûre & Précision', machineType: 'Piqueuse Plate (301)', description: 'Pour surpiqûre nervure régulière (Sirpikaj).', useCase: 'Col, Poignet, Rabat' },
    { id: 'g3', name: 'Pied Compensé (1/4 - 6mm)', category: 'Surpiqûre & Précision', machineType: 'Piqueuse Plate (301)', description: 'Pour surpiqûre large (Sebbat 0.5).', useCase: 'Plaquage poches, Jeans' },
    { id: 'g4', name: 'Pied Fermeture Invisible', category: 'Opérations Spéciales', machineType: 'Piqueuse Plate (301)', description: 'Pour poser les zips invisibles (Snsla Madfona).', useCase: 'Robe, Jupe, Pantalon' },
    { id: 'g5', name: 'Pied Unilatéral (Demi-Pied)', category: 'Opérations Spéciales', machineType: 'Piqueuse Plate (301)', description: 'Pour poser fermeture éclair standard ou passepoil.', useCase: 'Braguette, Coussins' },
    { id: 'g6', name: 'Guide Ourleur (Escargot)', category: 'Bordeurs & Ourleurs', machineType: 'Piqueuse Plate (301)', description: 'Pour faire un ourlet roulotté fin (Ghli R9i9).', useCase: 'Bas chemise, Foulard' },
    { id: 'g7', name: 'Pied Téflon (Plastique)', category: 'Matières Difficiles', machineType: 'Piqueuse Plate (301)', description: 'Pour matières glissantes ou collantes (Cuir, Skai).', useCase: 'Cuir, Simili, Vinyl' },
    { id: 'g8', name: 'Pied Fronceur', category: 'Fronces & Plis', machineType: 'Piqueuse Plate (301)', description: 'Pour froncer automatiquement (Tkrich/Kmmch).', useCase: 'Volants, Manches ballon' },
    { id: 'g9', name: 'Guide Aimanté', category: 'Guides & Jauges', machineType: 'Piqueuse Plate (301)', description: 'Guide mobile pour largeur couture fixe.', useCase: 'Toutes coutures droites' },
    { id: 'g10', name: 'Guide Passepoil', category: 'Opérations Spéciales', machineType: 'Piqueuse Plate (301)', description: 'Pour insérer un passepoil régulier.', useCase: 'Coussins, Poches, Cols' },
    { id: 'g11', name: 'Guide Élastique', category: 'Opérations Spéciales', machineType: 'Surjeteuse 4 Fils (514)', description: 'Pour poser élastique en tension (Lastik).', useCase: 'Ceinture, Lingerie' },
    { id: 'g12', name: 'Guide Ourlet Invisible', category: 'Bordeurs & Ourleurs', machineType: 'Surjeteuse 3 Fils (504)', description: 'Pour ourlet invisible bas de pantalon.', useCase: 'Pantalon Classique' },
    { id: 'g13', name: 'Guide Colletage', category: 'Bordeurs & Ourleurs', machineType: 'Colleteuse (602)', description: 'Pour poser bande de propreté ou biais (Bande).', useCase: 'T-shirt, Col' },
    { id: 'g14', name: 'Guide Ourlet (Bas)', category: 'Bordeurs & Ourleurs', machineType: 'Colleteuse (602)', description: 'Pour ourlet bas et manches (Ghli).', useCase: 'T-shirt, Polo' },
    { id: 'g15', name: 'Guide Ceinture', category: 'Guides & Jauges', machineType: 'Piqueuse Double Aig (316)', description: 'Pour montage ceinture (Samta).', useCase: 'Jeans, Pantalon' }
];

export const AUTO_SAVE_KEY = 'beramethode_autosave_v1';
export const LIBRARY_KEY = 'beramethode_library';
export const MANUAL_LINKS_BY_MODEL_KEY = 'beramethode_manual_links_by_model';
export const MACHINES_STORAGE_KEY = 'beramethode_machines_v1';
export const MACHINE_INSTANCES_KEY = 'beramethode_machine_instances';
export const MACHINE_FLEET_HISTORY_KEY = 'beramethode_machines_fleet_history_v1';
export const MAX_MACHINE_FLEET_HISTORY = 500;

export const defaultNavOrder = ['vuegenerale', 'dashboard', 'library', 'coupe', 'effectifs', 'gestionRh', 'planning', 'suivi', 'rendement', 'magasin', 'export', 'facturation', 'config', 'pageMachine', 'machin', 'catalogTemps', 'admin', 'sousTraitance'];

export const CATEGORY_TRANSLATIONS: Record<string, {fr:string,ar:string,en:string,es:string,pt:string,tr:string}> = {
  principal: {fr:'Principal',ar:'الرئيسية',en:'Main',es:'Principal',pt:'Principal',tr:'Ana'},
  production: {fr:'Production',ar:'الإنتاج',en:'Production',es:'Producción',pt:'Produção',tr:'Üretim'},
  rh: {fr:'RH',ar:'الموارد البشرية',en:'HR',es:'RRHH',pt:'RH',tr:'İK'},
  logistique: {fr:'Logistique',ar:'اللوجستيك',en:'Logistics',es:'Logística',pt:'Logística',tr:'Lojistik'},
  config: {fr:'Config',ar:'الإعدادات',en:'Config',es:'Config',pt:'Config',tr:'Yapılandırma'},
};

export const fmt = (n: number) => parseFloat(n.toFixed(1)).toString();

export const translations: Translations = {
  dr: { // Darija
    appTitle: "BERAMETHODE",
    subTitle: "حساب سعر التكلفة (Prix de Revient)",
    modelInfo: "معلومات الموديل & التكلفة",
    modelName: "اسم الموديل",
    sewingTime: "وقت الخياطة (دقيقة)",
    costMinute: "تكلفة الدقيقة",
    cutting: "فصالة",
    packing: "تغليف (Emballage)",
    totalTime: "المجموع",
    materials: "السلعة (Matière Première)",
    matName: "المادة",
    price: "الثمن",
    qtyUnit: "الكمية / الوحدة",
    total: "المجموع",
    addMat: "إضافة مادة",
    needs: "تقدير احتياجات الطلبية",
    needsDesc: "حساب السلعة + الميزانية",
    waste: "الخسارة (Waste)",
    orderQty: "الكمية المطلوبة",
    toBuy: "للشراء",
    realBudget: "ميزانية السلعة (Real)",
    theoCost: "تكلفة السلعة (النظري)",
    laborCost: "تكلفة اليد العاملة",
    totalBudget: "الميزانية الإجمالية",
    totalCost: "التكلفة الكلية",
    settings: "إعدادات الهوامش والضريبة",
    apply: "تطبيق",
    margeAtelier: "ربح المصنع %",
    tva: "الضريبة %",
    margeBoutique: "ربح المحل %",
    ticketTitle: "بطاقة التكلفة",
    docTitle: "ورقة تقنية (A4)",
    date: "التاريخ",
    totalMat: "مجموع السلعة",
    labor: "اليد العاملة",
    costPrice: "سعر التكلفة (P.R)",
    prodCost: "تكلفة الإنتاج",
    sellHT: "ثمن البيع (HT)",
    sellTTC: "ثمن البيع (TTC)",
    netProfit: "الربح الصافي",
    shopPrice: "ثمن المحل",
    print: "طباعة",
    excel: "تحميل Excel",
    pdf: "إعدادات PDF",
    auto: "أوتو",
    manual: "يدوي",
    companyName: "اسم الشركة (اضغط للتعديل)",
    companyAddress: "العنوان ورقم الهاتف...",
    companyLegal: "ICE: 000... | RC: 000... (المعلومات القانونية)",
    notes: "ملاحظات إضافية...",
    ref: "المرجع",
    viewTicket: "بطاقة",
    viewDoc: "وثيقة A4",
    uploadLogo: "اضغط لرفع اللوغو",
    pdfSettings: "إعدادات الطباعة PDF",
    orientation: "الاتجاه",
    portrait: "عمودي (عادي)",
    landscape: "أفقي (90 درجة)",
    colorMode: "الألوان",
    color: "ألوان (Color)",
    grayscale: "أبيض وأسود (N&B)",
    zoom: "الحجم (Echelle)",
    cancel: "إلغاء",
    download: "تحميل الآن",
    preview: "معاينة (Aperçu)",
    generating: "جاري التحضير...",
    orderNeedsTitle: "احتياجات الطلبية (Commande)",
    qtyToBuy: "الكمية للشراء",
    totalLine: "المجموع",
    loadingLib: "جاري تحميل النظام..."
  },
  fr: {
    appTitle: "BERAMETHODE",
    subTitle: "Calcul de Prix de Revient Industriel",
    modelInfo: "Infos Modèle & Coûts",
    modelName: "Nom du Modèle",
    sewingTime: "Temps Couture (min)",
    costMinute: "Coût Minute",
    cutting: "Coupe",
    packing: "Emballage",
    totalTime: "Total",
    materials: "Matières Premières",
    matName: "Matière",
    price: "Prix",
    qtyUnit: "Qté / Unité",
    total: "Total",
    addMat: "Ajouter Matière",
    needs: "Estimation des Besoins",
    needsDesc: "Calcul Matière + Budget",
    waste: "Majoration (Perte)",
    orderQty: "Qté Commande",
    toBuy: "À Acheter",
    realBudget: "Budget Matière (Réel)",
    theoCost: "Coût Matière (Théo)",
    laborCost: "Coût Main d'œuvre",
    totalBudget: "Budget Total",
    totalCost: "Coût Global",
    settings: "Marges & Taxes",
    apply: "Appliquer",
    margeAtelier: "Marge Atelier %",
    tva: "TVA %",
    margeBoutique: "Marge Boutique %",
    ticketTitle: "Fiche de Revient",
    docTitle: "Fiche Technique (A4)",
    date: "Date",
    totalMat: "Total Matière",
    labor: "Main d'œuvre",
    costPrice: "Prix de Revient",
    prodCost: "Coût de Production",
    sellHT: "Prix Vente (HT)",
    sellTTC: "Prix Vente (TTC)",
    netProfit: "Marge Nette",
    shopPrice: "Prix Boutique",
    print: "Imprimer",
    excel: "Télécharger Excel",
    pdf: "Config PDF",
    auto: "Auto",
    manual: "Manuel",
    companyName: "Nom de la Société (Cliquer pour éditer)",
    companyAddress: "Adresse et Téléphone...",
    companyLegal: "ICE: 000... | RC: 000... (Infos Légales)",
    notes: "Notes supplémentaires...",
    ref: "Réf",
    viewTicket: "Ticket",
    viewDoc: "Document A4",
    uploadLogo: "Cliquer pour Logo",
    pdfSettings: "Paramètres PDF",
    orientation: "Orientation",
    portrait: "Portrait",
    landscape: "Paysage (90°)",
    colorMode: "Couleurs",
    color: "Couleur",
    grayscale: "Noir & Blanc",
    zoom: "Échelle",
    cancel: "Annuler",
    download: "Télécharger",
    preview: "Aperçu",
    generating: "Génération...",
    orderNeedsTitle: "Besoins pour la Commande",
    qtyToBuy: "Qté à Acheter",
    totalLine: "Total Ligne",
    loadingLib: "Chargement..."
  },
  en: {
    appTitle: "BERAMETHODE",
    subTitle: "Cost Price Calculation",
    modelInfo: "Model Info & Costs",
    modelName: "Model Name",
    sewingTime: "Sewing Time (min)",
    costMinute: "Cost per Minute",
    cutting: "Cutting",
    packing: "Packing",
    totalTime: "Total",
    materials: "Raw Materials",
    matName: "Material",
    price: "Price",
    qtyUnit: "Qty / Unit",
    total: "Total",
    addMat: "Add Material",
    needs: "Order Needs Estimation",
    needsDesc: "Material Calc + Budget",
    waste: "Waste %",
    orderQty: "Order Qty",
    toBuy: "To Buy",
    realBudget: "Material Budget (Real)",
    theoCost: "Material Cost (Theo)",
    laborCost: "Labor Cost",
    totalBudget: "Total Budget",
    totalCost: "Total Cost",
    settings: "Margins & Taxes",
    apply: "Apply",
    margeAtelier: "Factory Margin %",
    tva: "VAT %",
    margeBoutique: "Shop Margin %",
    ticketTitle: "Cost Sheet",
    docTitle: "Technical Sheet (A4)",
    date: "Date",
    totalMat: "Total Materials",
    labor: "Labor",
    costPrice: "Cost Price",
    prodCost: "Production Cost",
    sellHT: "Sale Price (Ex. Tax)",
    sellTTC: "Sale Price (Inc. Tax)",
    netProfit: "Net Profit",
    shopPrice: "Retail Price",
    print: "Print",
    excel: "Download Excel",
    pdf: "PDF Setup",
    auto: "Auto",
    manual: "Manual",
    companyName: "Company Name...",
    companyAddress: "Address & Phone...",
    companyLegal: "ICE: 000... | RC: 000...",
    notes: "Additional notes...",
    ref: "Ref",
    viewTicket: "Ticket",
    viewDoc: "A4 Doc",
    uploadLogo: "Click for Logo",
    pdfSettings: "PDF Settings",
    orientation: "Orientation",
    portrait: "Portrait",
    landscape: "Landscape",
    colorMode: "Color Mode",
    color: "Color",
    grayscale: "Grayscale",
    zoom: "Scale",
    cancel: "Cancel",
    download: "Download",
    preview: "Preview",
    generating: "Generating...",
    orderNeedsTitle: "Order Requirements",
    qtyToBuy: "Qty to Buy",
    totalLine: "Line Total",
    loadingLib: "Loading..."
  },
  es: {
    appTitle: "BERAMETHODE",
    subTitle: "Cálculo de Precio de Coste",
    modelInfo: "Info Modelo y Costos",
    modelName: "Nombre del Modelo",
    sewingTime: "Tiempo Costura (min)",
    costMinute: "Costo por Minuto",
    cutting: "Corte",
    packing: "Embalaje",
    totalTime: "Total",
    materials: "Materias Primas",
    matName: "Material",
    price: "Precio",
    qtyUnit: "Cant. / Unidad",
    total: "Total",
    addMat: "Añadir Material",
    needs: "Estimación de Necesidades",
    needsDesc: "Cálculo Material + Presupuesto",
    waste: "Desperdicio %",
    orderQty: "Cant. Pedido",
    toBuy: "A Comprar",
    realBudget: "Presupuesto Mat. (Real)",
    theoCost: "Costo Mat. (Teórico)",
    laborCost: "Costo Mano de Obra",
    totalBudget: "Presupuesto Total",
    totalCost: "Costo Global",
    settings: "Márgenes e Impuestos",
    apply: "Aplicar",
    margeAtelier: "Margen Fábrica %",
    tva: "IVA %",
    margeBoutique: "Margen Tienda %",
    ticketTitle: "Hoja de Costos",
    docTitle: "Ficha Técnica (A4)",
    date: "Fecha",
    totalMat: "Total Materiales",
    labor: "Mano de Obra",
    costPrice: "Precio de Coste",
    prodCost: "Costo de Producción",
    sellHT: "Precio Venta (S. Imp)",
    sellTTC: "Precio Venta (C. Imp)",
    netProfit: "Beneficio Neto",
    shopPrice: "Precio Tienda",
    print: "Imprimir",
    excel: "Descargar Excel",
    pdf: "Config PDF",
    auto: "Auto",
    manual: "Manuel",
    companyName: "Nombre Empresa...",
    companyAddress: "Dirección y Teléfono...",
    companyLegal: "ICE: 000... | RC: 000...",
    notes: "Notas adicionales...",
    ref: "Ref",
    viewTicket: "Ticket",
    viewDoc: "Doc A4",
    uploadLogo: "Clic para Logo",
    pdfSettings: "Configuración PDF",
    orientation: "Orientación",
    portrait: "Vertical",
    landscape: "Horizontal",
    colorMode: "Color",
    color: "Color",
    grayscale: "Blanco y Negro",
    zoom: "Escala",
    cancel: "Cancelar",
    download: "Descargar",
    preview: "Vista Previa",
    generating: "Generando...",
    orderNeedsTitle: "Necesidades del Pedido",
    qtyToBuy: "Cant. a Comprar",
    totalLine: "Total Línea",
    loadingLib: "Cargando..."
  }
};

